// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBusinessApp.Infrastructure.DBContext;

#nullable disable

namespace MyBusinessAppDemo.Infrastructure.Migrations
{
    [DbContext(typeof(MyBusinessAppDbContext))]
    partial class MyBusinessAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accounts.Infrastructure.Entities.BusinessPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProviderNumber")
                        .HasColumnType("int");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BusinessPartners");
                });

            modelBuilder.Entity("Accounts.Infrastructure.Entities.BusinessPartnerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("BusinessPartnerTypes");
                });

            modelBuilder.Entity("Accounts.Infrastructure.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdressDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PostalCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StorageKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.PostalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("PostalCodes");
                });

            modelBuilder.Entity("BusinessPartnerBusinessPartnerType", b =>
                {
                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessPartnerTypesId")
                        .HasColumnType("int");

                    b.HasKey("BusinessPartnerId", "BusinessPartnerTypesId");

                    b.HasIndex("BusinessPartnerTypesId");

                    b.ToTable("BusinessPartnerBusinessPartnerType");
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.AdressSearchResult", b =>
                {
                    b.Property<string>("AdressDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryAlpha2Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_AdressSearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.BusinessPartnerSearchResult", b =>
                {
                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProviderNumber")
                        .HasColumnType("int");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_BusinessPartnerSearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.BusinessPartnerTypeSearchResult", b =>
                {
                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_BusinessPartnerTypeSearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.CompanySearchResult", b =>
                {
                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_CompanySearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.ContactSearchResult", b =>
                {
                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_ContactSearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.CountrySearchResult", b =>
                {
                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_CountrySearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.DocumentSearchResult", b =>
                {
                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_DocumentSearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.NoteSearchResult", b =>
                {
                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_NoteSearchResult", (string)null);
                });

            modelBuilder.Entity("Search.Contracts.SearchResults.PostalCodeSearchResult", b =>
                {
                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryAlpha2Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainObjectId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_PostalCodeSearchResult", (string)null);
                });

            modelBuilder.Entity("Accounts.Infrastructure.Entities.BusinessPartner", b =>
                {
                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("BusinessPartnerId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("BusinessPartnerId");

                            b1.ToTable("BusinessPartners");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts.Infrastructure.Entities.BusinessPartnerType", b =>
                {
                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("BusinessPartnerTypeId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("BusinessPartnerTypeId");

                            b1.ToTable("BusinessPartnerTypes");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerTypeId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts.Infrastructure.Entities.Contact", b =>
                {
                    b.HasOne("Accounts.Infrastructure.Entities.BusinessPartner", "BusinessPartner")
                        .WithMany("Contacts")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("ContactId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("BusinessPartner");

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Adress", b =>
                {
                    b.HasOne("Accounts.Infrastructure.Entities.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BaseData.Infrastructure.Entities.Company", null)
                        .WithMany("Adresses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BaseData.Infrastructure.Entities.PostalCode", "PostalCode")
                        .WithMany()
                        .HasForeignKey("PostalCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("AdressId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("AdressId");

                            b1.ToTable("Adresses");

                            b1.WithOwner()
                                .HasForeignKey("AdressId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Company", b =>
                {
                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Country", b =>
                {
                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("CountryId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Document", b =>
                {
                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("DocumentId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Note", b =>
                {
                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("NoteId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.PostalCode", b =>
                {
                    b.HasOne("BaseData.Infrastructure.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("BusinessAppFramework.Domain.DomainObjects.HistoryInfo", "HistoryInfo", b1 =>
                        {
                            b1.Property<int>("PostalCodeId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("LastModifiedById")
                                .HasColumnType("int");

                            b1.Property<string>("LastModifiedByName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("PostalCodeId");

                            b1.ToTable("PostalCodes");

                            b1.WithOwner()
                                .HasForeignKey("PostalCodeId");
                        });

                    b.Navigation("Country");

                    b.Navigation("HistoryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessPartnerBusinessPartnerType", b =>
                {
                    b.HasOne("Accounts.Infrastructure.Entities.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounts.Infrastructure.Entities.BusinessPartnerType", null)
                        .WithMany()
                        .HasForeignKey("BusinessPartnerTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts.Infrastructure.Entities.BusinessPartner", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("BaseData.Infrastructure.Entities.Company", b =>
                {
                    b.Navigation("Adresses");
                });
#pragma warning restore 612, 618
        }
    }
}
